<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Item Issuance Receipt - Request #{{ $request->id }}</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            max-width: 800px;
            margin: 0 auto;
            padding: 20px;
            line-height: 1.6;
        }
        .header {
            text-align: center;
            border-bottom: 2px solid #333;
            padding-bottom: 20px;
            margin-bottom: 30px;
        }
        .header h1 {
            margin: 0;
            color: #333;
        }
        .header p {
            margin: 5px 0;
            color: #666;
        }
        .info-section {
            margin-bottom: 30px;
        }
        .info-section h2 {
            color: #333;
            border-bottom: 1px solid #ddd;
            padding-bottom: 5px;
        }
        .info-grid {
            display: grid;
            grid-template-columns: 1fr 1fr;
            gap: 20px;
        }
        .info-item {
            margin-bottom: 10px;
        }
        .info-item strong {
            display: inline-block;
            width: 120px;
        }
        .items-table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }
        .items-table th, .items-table td {
            border: 1px solid #ddd;
            padding: 12px;
            text-align: left;
        }
        .items-table th {
            background-color: #f5f5f5;
            font-weight: bold;
        }
        .footer {
            margin-top: 40px;
            text-align: center;
            color: #666;
            font-size: 14px;
        }
        .signature-section {
            margin-top: 40px;
            display: flex;
            justify-content: space-between;
        }
        .signature-box {
            width: 200px;
            text-align: center;
        }
        .signature-line {
            border-top: 1px solid #333;
            margin-top: 40px;
            padding-top: 5px;
        }
        @media print {
            body { margin: 0; }
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>Item Issuance Receipt</h1>
        <p>Request ID: #{{ $request->id }}</p>
        <p>Generated on: {{ now()->format('F j, Y \a\t g:i A') }}</p>
    </div>

    <div class="info-section">
        <h2>Requester Information</h2>
        <div class="info-grid">
            <div>
                <div class="info-item">
                    <strong>Name:</strong> {{ $user->username }}
                </div>
                <div class="info-item">
                    <strong>Department:</strong> {{ $user->department ?? 'N/A' }}
                </div>
            </div>
            <div>
                <div class="info-item">
                    <strong>Request Date:</strong> {{ $request->created_at->format('F j, Y \a\t g:i A') }}
                </div>
                <div class="info-item">
                    <strong>Approved Date:</strong> {{ $request->approved_at->format('F j, Y \a\t g:i A') }}
                </div>
            </div>
        </div>
    </div>

    <div class="info-section">
        <h2>Request Details</h2>
        <div class="info-item">
            <strong>Message:</strong> {{ $request->message }}
        </div>
    </div>

    <div class="info-section">
        <h2>Issued Items</h2>
        <table class="items-table">
            <thead>
                <tr>
                    <th>Barcode</th>
                    <th>Product Name</th>
                    <th>Status</th>
                </tr>
            </thead>
            <tbody>
                @foreach($items as $item)
                <tr>
                    <td>{{ $item->barcode }}</td>
                    <td>{{ $item->product_name }}</td>
                    <td>(Issued)</td>
                </tr>
                @endforeach
            </tbody>
        </table>
    </div>

    <div class="signature-section">
        <div class="signature-box">
            <div class="signature-line">
                Requester Signature
            </div>
        </div>
        <div class="signature-box">
            <div class="signature-line">
                Admin/Issuer Signature
            </div>
        </div>
    </div>

    <div class="footer">
        <p>This receipt serves as proof of item issuance. Please keep this document for your records.</p>
        <p>Generated by Inventory Management System</p>
    </div>
</body>
</html>